export const POST_PHIM_ADMIN_REQUEST = "POST_PHIM_REQUEST";
export const POST_PHIM_ADMIN_SUCCESS = "POST_PHIM_SUCCESS";
export const POST_PHIM_ADMIN_ERROR = "POST_PHIM_ADMIN_ERROR";

export const GET_LIST_PHANTRANG_ADMIN_REQUEST = "GET_LIST_PHANTRANG_REQUEST";
export const GET_LIST_PHANTRANG_ADMIN_SUCCESS = "GET_LIST_PHANTRANG_SUCCESS";
export const GET_LIST_PHANTRANG_ADMIN_ERROR = "GET_LIST_PHANTRANG_ERROR";

export const UPDATE_PHIM_ADMIN_REQUEST = "UPDATE_PHIM_REQUEST";
export const UPDATE_PHIM_ADMIN_SUCCESS = "UPDATE_PHIM_SUCCESS";
export const UPDATE_PHIM_ADMIN_ERROR = "UPDATE_PHIM_ERROR";

export const DELETE_PHIM_ADMIN_REQUEST = "DELETE_PHIM_REQUEST";
export const DELETE_PHIM_ADMIN_SUCCESS = "DELETE_PHIM_SUCCESS";
export const DELETE_PHIM_ADMIN_ERROR = "DELETE_PHIM_ERROR";

export const GET_LISTMOVIE_ADMIN_REQUEST = "GET_LISTMOVIE_REQUEST_ADMIN";
export const GET_LISTMOVIE_ADMIN_SUCCESS = "GET_LISTMOVIE_SUCCESS_ADMIN";
export const GET_LISTMOVIE_ADMIN_ERROR = "GET_LISTMOVIE_ERROR_ADMIN";
