export const REQUEST_BOOKING_SUCCESS="REQUEST_BOOKING_API";
export const REQUEST_BOOKING_FAILURE="REQUEST_BOOKING_FAILURE";
export const REQUEST_DAT_VE="REQUEST_DAT_VE";
export const REQUEST_DAT_VE_FAILURE="REQUEST_DAT_VE_FAILURE";
export const REQUEST_API_BOOKING = "REQUEST_API_BOOKING";
export const IS_CHECKOUT = "IS_CHECKOUT";
export const SET_CHECKOUT ="SET_CHECKOUT";