export const DANGNHAP_REQUEST = "DANGNHAP_REQUEST";
export const DANGNHAP_REQUEST_SUCCESS = "DANGNHAP_REQUEST_SUCCESS";
export const DANGNHAP_REQUEST_ERROR = "DANGNHAP_REQUEST_ERROR";
export const DANGKY_REQUEST = "DANGKY_REQUEST";
export const DANGKY_REQUEST_SUCCESS = "DANGKY_REQUEST_SUCCESS";
export const DANGKY_REQUEST_ERROR = "DANGKY_REQUEST_ERROR";
