export const GET_LISTUSER_PHANTRANG_REQUEST = "GET_LISTUSER_PHANTRANG";
export const GET_LISTUSER_PHANTRANG_SUCCESS = "GET_LISTUSER_PHANTRANG_SUCCESS";
export const GET_LISTUSER_PHANTRANG_ERROR = "GET_LISTUSER_PHANTRANG_ERROR";

export const UPDATE_THONGTIN_USER_REQUEST = "UPDATE_THONGTIN_USER_REQUEST";
export const UPDATE_THONGTIN_USER_SUCCESS = "UPDATE_THONGTIN_USER_SUCCESS";
export const UPDATE_THONGTIN_USER_ERROR = "UPDATE_THONGTIN_USER_ERROR";

export const DELETE_NGUOIDUNG_REQUEST = "DELETE_NGUOIDUNG_REQUEST";
export const DELETE_NGUOIDUNG_SUCCESS = "DELETE_NGUOIDUNG_SUCCESS";
export const DELETE_NGUOIDUNG_ERROR = "DELETE_NGUOIDUNG_ERROR";

export const POST_THEM_NGUOIDUNG_REQUEST = "POST_THEM_NGUOIDUNG_REQUEST";
export const POST_THEM_NGUOIDUNG_SUCCESS = "POST_THEM_NGUOIDUNG_SUCCESS";
export const POST_THEM_NGUOIDUNG_ERROR = "POST_THEM_NGUOIDUNG_ERROR";

export const GET_DANHSACH_USER_REQUEST = "GET_DANHSACH_USER";
export const GET_DANHSACH_USER_SUCCESS = "GET_DANHSACH_USER_SUCCESS";
export const GET_DANHSACH_USER_ERROR = "GET_DANHSACH_USER_ERROR";

export const GET_THONGTIN_USER_REQUEST = "GET_THONGTIN_USER_REQUEST";
export const GET_THONGTIN_USER_SUCCESS = "GET_THONGTIN_USER_SUCCESS";
export const GET_THONGTIN_USER_ERROR = "GET_THONGTIN_USER_ERROR";
